### ISSUE TITLE
Short explain how to use?

### ISSUE THREAD

**Issue by OMGerEDU** [elvis-ndubuisi/media-downloader-api#1]
Hi, I downloaded it, also the required modules, but I have zero clue how to operate it, 
Do I need to docket it in order to work? or how does it works?

**Comment by elvis-ndubuisi** [comment]
ooh. Hello?
The project uses the ytdl-core package (and some basic npm packages like express and helmet). If you've cloned the project, you will have to self-host it. I used the cyclic hosting platform (for free and easy setup). if you wish to use the API, I will update the readme file immediately. Also, this project setup has downsides and issues, which I will discuss in the README.md file. 
I appreciate your interest in this project. I really appreciate it.
